---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: hyprblue
# description will be included in the image's metadata
description: Highly opnionated hyprland custom image

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/sericea-main
image-version: 43 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - sdegler/hyprland
        - erikreider/SwayNotificationCenter
        - errornointernet/packages
        - tofik/nwg-shell
        - alternateved/eza
        - lihaohong/yazi
        - opuk/bottom
        - atim/lazygit
        - atim/lazydocker
        - wezfurlong/wezterm-nightly
        - scottames/ghostty
    install:
      packages:
        - bc
        - curl
        - findutils
        - gawk
        - git
        - grim
        - gvfs
        - gvfs-mtp
        - hyprpolkitagent
        - ImageMagick
        - inxi
        - jq
        - kitty
        - kvantum
        - nano
        - network-manager-applet
        - openssl
        - pamixer
        - pavucontrol
        - pipewire-alsa
        - pipewire-utils
        - playerctl
        - python3-requests
        - python3-pip
        - python3-pyquery
        - qt5ct
        - qt6ct
        - qt6-qtsvg
        - rofi
        - slurp
        - swappy
        - unzip
        - waybar
        - wget2
        - wl-clipboard
        - wlogout
        - xdg-user-dirs
        - xdg-utils
        - yad
        - brightnessctl
        - btop
        - cava
        - loupe
        - fastfetch
        - gnome-system-monitor
        - mousepad
        - mpv
        - mpv-mpris
        - nvtop
        - qalculate-gtk
        - nwg-displays
        - cliphist
        - nwg-look
        - SwayNotificationCenter
        - pamixer
        - swww
        - wallust 
    remove:
      packages:
        - aylurs-gtk-shell
        - dunst
        - mako
        - rofi

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: []
          # - org.mozilla.firefox
          # - org.gnome.Loupe
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
